apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: resource-tracker
type: Opaque
stringData:
  DATABASE_PASSWORD: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_USER: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: resource-tracker
type: Opaque
stringData:
  JWT_SECRET: change_this_secret_in_production
  CHAT_ENCRYPTION_KEY: 4698e7cef7ccbbfa98cf7b8fdcb333a697949df021f1cf3a65e2166618f1da5d
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
