apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-tracker

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespaces/namespace.yaml
  - configmaps/app-config.yaml
  - configmaps/postgres-init.yaml
  - secrets/secrets.yaml
  - pvcs/pvc.yaml
  - postgres/postgres.yaml
  - postgres/pgadmin.yaml
  - rabbitmq/rabbitmq.yaml
  - services/auth-service.yaml
  - services/project-service.yaml
  - services/timesheet-service.yaml
  - services/notification-service.yaml
  - services/reporting-service.yaml
  - services/chat-service.yaml
  - services/meeting-service.yaml
  - services/api-gateway.yaml
  - services/frontend.yaml
  - services/network-policies.yaml
  - ingress/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: resource-tracker
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  org.example/team: platform
  org.example/project: resource-tracker